spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: root91
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Создание/обновление схемы базы данных
    show-sql: true      # Вывод SQL-запросов в лог
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
